name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: integration test 1
      id: integration-test-1
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 2
        setup-command: sh config_test.sh "test_union_integration_disjoint"
    - name: integration test 2
      id: integration-test-2
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: sh config_test.sh "test_union_integration_overlap"
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INTEGRATION-TEST-1_RESULTS: "${{steps.integration-test-1.outputs.result}}"
        INTEGRATION-TEST-2_RESULTS: "${{steps.integration-test-2.outputs.result}}"
      with:
        runners: integration-test-1,integration-test-2
