name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_union_integration_disjoint
      id: test_union_integration_disjoint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_union_integration_disjoint
        setup-command: ''
        command: sh config_test.sh "test_union_integration_disjoint"
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_UNION_INTEGRATION_DISJOINT_RESULTS: "${{steps.test_union_integration_disjoint.outputs.result}}"
      with:
        runners: test_union_integration_disjoint
