name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: integration tests
      id: integration-tests
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 2
        setup-command: sh config_test.sh "test_*integration*"
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INTEGRATION-TESTS_RESULTS: "${{steps.integration-tests.outputs.result}}"
      with:
        runners: integration-tests
