name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: integration test 3
      id: integration-test-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: integration test 3
        setup-command: ''
        command: sh config_test.sh "test_union_integration_overlap"
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INTEGRATION-TEST-3_RESULTS: "${{steps.integration-test-3.outputs.result}}"
      with:
        runners: integration-test-3
